### ISSUE TITLE
Jenkins Docker

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#17]
### AzureDevOps
https://dev.azure.com/AzureDevOpsKats/AzureDevOpsKats

- [ ] 1 - Jenkins Docker
Intergrate  Jenkins Job into Azure DevOps
https://jenkins.navigatorglass.com/job/AzureDevOpsKats/job/AzureDevOpsKats-base/

See:

Create personal access tokens to authenticate access
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts

Tutorial: Integrate your Jenkins CI jobs with Azure Pipelines CD to Azure
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/integrate-jenkins-vsts-cicd?view=vsts

![untitled](https://user-images.githubusercontent.com/887805/48663535-a96bb100-ea5f-11e8-8b5d-6e59997ebebe.png)

**Comment by dmitryint** [comment]
<img width="764" alt="2018-11-19 11 41 40" src="https://user-images.githubusercontent.com/9825180/48695431-2b8adf80-ebf0-11e8-8253-a7afd32747fc.png">

@stuartshay To do this, we need to switch the Jenkins authentication method from GitHub to built-in

**Comment by dmitryint** [comment]
https://dev.azure.com/AzureDevOpsKats/AzureDevOpsKats/_release?definitionId=2&view=mine&_a=releases
https://jenkins.navigatorglass.com/job/AzureDevOpsKats/job/AzureDevOpsKats-base-TFS/

@stuartshay It looks like this will only work with a free style configuration.

**Comment by stuartshay** [comment]
This is Great, 
 I will wait till they update this so if supports a better Auth Scheme
