### ISSUE TITLE
Azure Devops - DNS Registration

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#23]
When AKS is created need to Auto Register DNS Name using Wild Card Cert.

### *.azuredevopskats.com
(Name is Registerd on DNSimple)

- [ ] 1 - Setup Let's Encrypt Mapped to  Wild Card DNS  
 
When User Create a new job they can enter the Sub-Domain

```
testing,azuredevopskats.com
```

- [ ] 2 - When the Cluster is Created the Subdomain Should also create an K8s Namespace using the same name

![untitled](https://user-images.githubusercontent.com/887805/49268543-fbccaa80-f42d-11e8-9e6e-d94d3e71cb8c.png)

**Comment by dmitryint** [comment]
@stuartshay Unable to accès your DNSimple account: `sshay@yahoo.com`

**Comment by stuartshay** [comment]
Tried a few times the reset password not working 

Will try again latter

**Comment by stuartshay** [comment]
Working on it emailed them, account might have been locked with try on the VM once I get response

**Comment by dmitryint** [comment]
@stuartshay 
AKS will not work with LE wildcard certificates for domains hosted on DNSimple. There are currently no services to support this.

**Comment by stuartshay** [comment]
NP anything that works is good a static name is good just want something I can bring up and tear down

I am not sure but is AKS deprecated for now it is fine

**Comment by dmitryint** [comment]
@stuartshay Done. I also added a test deployment of DokuWiki.
