### ISSUE TITLE
Azure DevOps - K8s

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#38]
- [ ] 1 - On AKS Build Create Job that will destroy AKS in 12 Hours 

![untitled](https://user-images.githubusercontent.com/887805/49705517-be65db00-fbec-11e8-859e-78befd0c2d2b.png)

 - [ ] 2  - Enable kubectl - Remote Execution from the Command Line,  
Want to run kubectl from my machine using ssh key stored in Key Vault 
(Firewall Rules can be added latter to exclude/include remote ip's)

 - [ ] 3 -  Enable port for K8s Dashboard (Using SSH Key)

```
https://webui.azuredevopskats.com
```

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

_Job Start Stop_
Replacing Azure Automation using Azure CLI and Azure Devops

https://gregorsuttie.com/2019/05/08/replacing-azure-automation-using-azure-cli-and-azure-devops/

**Comment by dmitryint** [comment]
> 1 - On AKS Build Create Job that will destroy AKS in 12 Hours

The environment should be destroyed at 0:00 EST at the moment.
In order to implement auto destruction in a certain number of hours, we will have to use some services to store the state. 

>2 - Enable kubectl - Remote Execution from the Command Line,
Want to run kubectl from my machine using ssh key stored in Key Vault
(Firewall Rules can be added latter to exclude/include remote ip's)

At the moment, you can access the kubectl/Dashboard using az cli.

```
az aks get-credentials --resource-group AzureDevOpsKatsAzureContainerServicesd339b79c --name test
```

```
az aks browse --resource-group AzureDevOpsKatsAzureContainerServicesd339b79c --name test
```

<img width="1652" alt="2018-12-10 16 14 49" src="https://user-images.githubusercontent.com/9825180/49734894-c24e3780-fc96-11e8-8a49-1f5c08aeb8f2.png">

@stuartshay

**Comment by stuartshay** [comment]
Ok this is good for now

**Comment by dmitryint** [comment]
Well, this idea will works only with normal wildcard certificate, non Let's Encrypt.

```
I1210 15:07:15.308385       1 sync.go:288] Error issuing certificate for default/azuredevopskats-com: error getting certificate from acme server: acme: urn:ietf:params:acme:error:rateLimited: Error finalizing order :: too many certificates already issued for exact set of domains: *.azuredevopskats.com,azuredevopskats.com: see https://letsencrypt.org/docs/rate-limits/
```

**Comment by dmitryint** [comment]
@stuartshay https://www.ssl2buy.com/alphassl-wildcard.php
from $40/year

**Comment by stuartshay** [comment]
What should I get , I think the dnsimple is the same price we need a wild card cert

**Comment by dmitryint** [comment]
<img width="794" alt="2018-12-11 22 12 50" src="https://user-images.githubusercontent.com/9825180/49823963-f3f7f900-fd91-11e8-9e55-54c5415644c1.png">
 
They offer a wildcard certificate for $100

Btw, you should bought certificate with Common Name: `azuredevopskats.com` and SAN: `*.azuredevopskats.com`

**Comment by stuartshay** [comment]
Ok let me see if I can get a new cert

**Comment by stuartshay** [comment]
I see this site has list of Certs,  Just need something that work best,
 https://www.ssldragon.com/ssl-certificates/filters/secures/68/?gclid=Cj0KCQiA3b3gBRDAARIsAL6D-N-9rbGem9mwv4GiMBk82IUtIzVXB-imtVeif_KjobOq-2vzN8KQXwQaAg1QEALw_wcB

**Comment by dmitryint** [comment]
<img width="356" alt="2018-12-12 10 44 12" src="https://user-images.githubusercontent.com/9825180/49854341-e4f96100-fdfa-11e8-891b-9f7ea309d2be.png">

**Comment by dmitryint** [comment]
@stuartshay certificate updated. Now it's works.
