### ISSUE TITLE
Azure Devops - Infrastucture

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#4]
## Azure Devops Pipeline Project
https://dev.azure.com/AzureDevOpsKats/AzureDevOpsKats/

  - [x]  1 Deploy JSON ARM Infrastructure Templates -
           https://github.com/stuartshay/AzureDevOpsKats/tree/master/infastructure/arm_release
          -- AppService
          -- WebSite 

![capture](https://user-images.githubusercontent.com/887805/47598094-0c888d00-d965-11e8-86f1-43989612873c.PNG)

  - [x]  2 Create and Deploy Templates for the Following Services 
          -- Storage Account & Blob Storage 
          -- Key Vault 

  - [ ]  3  Create & Deploy Azure Container Services 

https://hub.docker.com/r/stuartshay/azuredevopskats/tags/

- Create Script to Deploy App 
```
docker pull stuartshay/azuredevopskats:devops
```

**Comment by dmitryint** [comment]
@stuartshay I need you to run a command: `az ad sp create-for-rbac --role="Contributor" \
  --scopes="/subscriptions/09e01a7d-07d4-43ee-80c7-8b2c0d7ec41f/resourceGroups/AzureDevOpsKatsGroup"
`
I don't have enough permissions to do this.
Please send me appID and password privately.

**Comment by stuartshay** [comment]
I tried to run
```
az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/09e01a7d-07d4-43ee-80c7-8b2c0d7ec41f/resourceGroups/AzureDevOpsKatsGroup" 
```
![capture](https://user-images.githubusercontent.com/887805/47827842-784c6a80-dd56-11e8-834e-c80085caeccd.PNG)

```Credentials have expired due to inactivity. Please run 'az login'```

1) What do I need to give you access 
2)  I can turn on VM and I will login with my account and you can give your self necessary permissions.

**Comment by dmitryint** [comment]
The key for this command has been sent privately.

```
az acs kubernetes get-credentials \
    --ssh-key-file arm_release/key/ssh-key \
    --resource-group=AzureDevOpsKatsGroup \
    --name=containerservice-AzureDevOpsKatsGroup
```

**Comment by stuartshay** [comment]
Not Sure the Azure PowerShell is the best way to do this I found some links using Terraform,  Open to anything that works best. 

- Would Like to Create this Infrastructure so I can on Bring Up and Tear Down the Container Service
(Anything that works i am fine with)

### Static Resource Group -> AzureDevOpsKats_Infra
Key Vault, Blob Storage, (Anything else necessary)

### Bring Up/Tear Resource Group -> AzureDevOpsKats_RandomName

- Azure Container Service 

#### Links 
https://open.microsoft.com/2018/10/23/microsoft-and-hashicorp-collaborate-to-build-a-better-terraform-provider/
https://pleasereleaseme.net/create-an-azure-devops-services-self-hosted-agent-in-azure-using-terraform-cloud-init-and-azure-devops-pipelines/


Terraform Build & Release Tasks
https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform

**Comment by dmitryint** [comment]
@stuartshay Done.

https://dev.azure.com/AzureDevOpsKats/AzureDevOpsKats/_build/results?buildId=317&_a=summary

**Comment by stuartshay** [comment]
Closing Issue, Will Create new Issue
