### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#571]
- [x] 1 - ALB 

Application Load Balancer  (Choose Best)  

Add 2 Containers to Task (Options to Manually Adjust in workflow if possible)

- [x] 2 - Health Check Step
- Add Similar Functionality as Health Check Step in Microservice Project

Echo Output Results of the Health Check - Additional Logic will be applied in Additional Tasks

https://github.com/stuartshay/MicroService/blob/master/.github/workflows/actions.yml#L160

### TIPS
View the Container Health Check

``` 
http://localhost:5000/health
```

![image](https://user-images.githubusercontent.com/887805/148669232-9a8bd131-6883-4ec2-b4f5-a3db75de5c78.png)

**Comment by chiplonton** [comment]
Application Load Balancer (Choose Best) --> we only support ALB for master as production, to save cost, we don't need to setup it for develop branch
`Add 2 Containers to Task (Options to Manually Adjust in workflow if possible)` --> please refer to this params on workflow `MASTER_ECS_DESIRED_COUNT`, default `2` tasks

**Comment by stuartshay** [comment]
Was Unable to Get the Develop Branch to Deploy I see that the Master Branch Runs. I did not rerun the deployment for Devlop

I applied a Configuration Change, it should do nothing for now

Can you Set the ENV Variable  
```
ASPNETCORE_ENVIRONMENT AwsEcs
```

Also Can you add the Parameter Store Permissions, 
https://github.com/aws/aws-dotnet-extensions-configuration#parameter-store

**Nothing is Setup Yet.** Just Require the Permissions to be there for development, 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "SSMPermissionStatement",
            "Effect": "Allow",
            "Action": "ssm:GetParameters",
            "Resource": "arn:aws:ssm:${Region}:${Account}:parameter/${ParameterNamePrefix}*"
        }
    ]
}
```

**Comment by chiplonton** [comment]
all is fixed and added, please help to recheck it again
