### ISSUE TITLE
AWS SystemsManager - Permissions

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#588]
Required Permissions     
https://github.com/aws/aws-dotnet-extensions-configuration

Uncomment this code and view in Cloudwatch logging.      
https://github.com/stuartshay/AzureDevOpsKats/blob/master/src/AzureDevOpsKats.Web/Program.cs#L50

```
Unhandled exception. Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementException: 
User: arn:aws:sts::816939196156:assumed-role/devopskats-container/f78539c986f7468ea60c8934e33be57d is not 
authorized to perform: ssm:GetParametersByPath on resource: 
arn:aws:ssm:us-east-1:816939196156:parameter/devopskats 
because no identity-based policy allows the ssm:GetParametersByPath action
```

**Comment by chiplonton** [comment]
I think the issue is fixed, please help to recheck

**Comment by stuartshay** [comment]
Works, The Code Now Reads from the AWS Parameter Store,  Will need to further enhance so Configuration is based by Environments
