### ISSUE TITLE
ENV Variable by Cluster/Environment 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#594]
Set the following ENV Variables by Cluster. 

The Application needs to determine what Cluster it is running on. once this is available, data will read from the parameter/secrets store.

**Mater Branch:**
```
CLUSTER_NAME: master
SYSTEMS_MANAGER_RELOAD: 360
ASPNETCORE_ENVIRONMENT=AwsEcs  (Existing does not require change)

```
**Develop Branch:**
```
CLUSTER_NAME: develop
SYSTEMS_MANAGER_RELOAD: 60
ASPNETCORE_ENVIRONMENT=AwsEcs (Existing does not require change)
```

Develop Branch: (All ways default to Development)

**Notes:**  Future Milestone Capture Log Entry in Cloud Watch

**Comment by chiplonton** [comment]
this is done
![image](https://user-images.githubusercontent.com/95140051/149860322-e59d043c-12ef-4931-86a7-cc7b8c3749fb.png)

**Comment by stuartshay** [comment]
Completed 

![image](https://user-images.githubusercontent.com/887805/150026368-f11c3322-85e7-4a7c-8402-8a11033c69f3.png)
