### ISSUE TITLE
 Standard naming convention

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#614]
Document all security groups, logging and infrastructure 

- [ ] 1 - **Logging:**

![image](https://user-images.githubusercontent.com/887805/151290033-6a94007f-1c0b-4248-9406-936d14e2fc40.png)

Rename to

```
project-environment
```

```
-- Existing to be renamed --

master-devops-> devopskats-master  
develop-devops -> devopskats-devlop

Examples
devopskats-master-worker
devopskats-master-api
```

- [ ] 2 - **Parameter Store:**
Add the following to the  Teraform Script to Create If does not exist (Leave Empty)
If Exists do not modify

```
/devopskats/master/smtp/password	
/devopskats/master/smtp/port	
/devopskats/master/smtp/server	
/devopskats/master/smtp/username


/devopskats/develop/smtp/password	
/devopskats/develop/smtp/port	
/devopskats/develop/smtp/server	
/devopskats/develop/smtp/username
```

**Comment by chiplonton** [comment]
#1, done
-- Existing to be renamed --

master-devops-> devopskats-master  
develop-devops -> devopskats-devlop

#2, done as well
