### ISSUE TITLE
React - Front End

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/AzureDevOpsKats#86]
- [ ] 1 - Server Side Validation on the Submitting Photo
- [ ] 2 - Add Toast (Edit, Delete, Created)

- [ ] 3 - Design Work Pager

- Remove Top Pager, Center on Bottom,  Add First - Last  
- Formatting Records & Layout 
- Make Layout more professional looking  (Delete. Edit Buttons) 

![Capture](https://user-images.githubusercontent.com/887805/60369080-85daf280-99c0-11e9-913c-03d94d294484.PNG)
 
![Capture](https://user-images.githubusercontent.com/887805/60369181-cfc3d880-99c0-11e9-8ec3-1377fafd5956.PNG)

**Comment by JPerfectSolution** [comment]
fixed all

**Comment by stuartshay** [comment]
1- Server Side Validation is not correct

See: 
https://github.com/stuartshay/ImageGallery.Client/blob/Auth/src/ImageGallery.Client/Apis/GalleryApiCommandController.cs#L60

2 - When Single Record should be formatted on Top Row

![Capture](https://user-images.githubusercontent.com/887805/60384745-b9189280-9a4f-11e9-8654-8ed296b53715.PNG)

3- When on First/Last Page ( Last/First Buttons Disable) 
![Capture](https://user-images.githubusercontent.com/887805/60384788-32b08080-9a50-11e9-92a0-a7faeaf5c16d.PNG)

**Comment by JPerfectSolution** [comment]
fixed 2, 3, 4, 5
